### ISSUE TITLE
Waterdrop Job Management UI

### ISSUE THREAD

**Issue by garyelephant** [InterestingLab/seatunnel#338]
Job 的启停目前需要自己管理，以后会做Job Web UI，现征集相关需求，留言即可。

（1）管理任务列表
（2）起停任务
（3）查看任务进度
（4）wd app 监控报警的管理

---

参考：
（1）EasyScheduler 怎么样？https://github.com/analysys/EasyScheduler

**Comment by garyelephant** [comment]
+1

**Comment by Tasselmi** [comment]
添加一个需求：任务之间的依赖关系，比如A执行完了才能执行B和C等等~

**Comment by garyganyang** [comment]
添加一个需求: 可以查看 input, filter, ouput等每个步骤的运行状态, 在哪个步骤发生了错误, 可以查看具体是什么错误, 可以运行到指定 filter 或 output, 可以预览每个步骤(filter)的输出结果

**Comment by liangpingliu** [comment]
还是各司其职的比较好，任务调度的事情还是让调度平台去做比较合适，可以让dolphinscheduler适配下waterdrop，如果自己做job管理页面要是能做到任务流管理也是ok，不然如果参照datax-web项目只是做了任务定时调度，感觉有点鸡肋。
