### ISSUE TITLE
[Apache] check whether seatunnel is a suitable project name

### ISSUE THREAD

**Issue by dailidong** [InterestingLab/seatunnel#682]
please refer to the apache related doc for the project NAMING process[1]

1: http://www.apache.org/foundation/marks/naming.html

**Comment by dailidong** [comment]
I have checked the following sites:

1、Trademarkia shows just 0 result
     http://www.trademarkia.com/trademarks-search.aspx?tn=seatunnel

2、No other software showed in Google search
     https://www.google.com/search?q=seatunnel

3、GitHub shows only the Apache project seatunnel, and projects in seatunnel ecosystem, such as other extension.
     https://github.com/search?q=seatunnel&ref=commandbar

4、No result in SF
     https://sourceforge.net/directory/os:mac/freshness:recently-updated/?q=seatunnel

5、No result in OpenHub
     https://www.openhub.net/p?query=seatunnel&sort=relevance

6、No result in uspto
     https://search.uspto.gov/search?query=seatunnel&op=Search&affiliate=web-sdmg-uspto.gov

7、No results for seatunnel in Google Code
	https://opensource.google/projects/search?q=seatunnel

8、No other software showed in Bing search
	https://www.bing.com/search?q=seatunnel

9、No other software showed in Yahoo search
	https://search.yahoo.com/search?p=seatunnel

**Comment by CalvinKirs** [comment]
check site : http://wcjs.sbj.cnipa.gov.cn/
![image](https://user-images.githubusercontent.com/16631152/142186216-0185d279-18de-49b8-91f4-85db4611f4d0.png)
![image](https://user-images.githubusercontent.com/16631152/142186248-033410ca-f2eb-464e-8de9-a769a082feff.png)

**Comment by CalvinKirs** [comment]
done
