### ISSUE TITLE
[Feature][CheckStyle] Add CheckStyle support

### ISSUE THREAD

**Issue by yx91490** [InterestingLab/seatunnel#706]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add checkstyle support to make code style more uniform. 
firstly we should add a checkstyle.xml that obey the style in existing codes(maybe the default style within Intellij Idea ?), and then add maven-checkstyle-plugin to pom.xml that enabled by default.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
@yx91490 Would you like to submit PR for this? if you do not like to do I would submit and add this feature

**Comment by wuchunfu** [comment]
I'm interested in this. I want to try it

**Comment by yx91490** [comment]
> @yx91490 Would you like to submit PR for this? if you do not like to do I would submit and add this feature

OK. there is a template that I think you can reference although I haven't try it : https://github.com/apache/servicecomb-java-chassis/blob/master/etc/intellij-java-google-style.xml

**Comment by wuchunfu** [comment]
> > [@yx91490](https://github.com/yx91490) Would you like to submit PR for this? if you do not like to do I would submit and add this feature

> OK. there is a template that I think you can reference although I haven't try it : https://github.com/apache/servicecomb-java-chassis/blob/master/etc/intellij-java-google-style.xml

OK.

**Comment by zhongjiajie** [comment]
Hi @wuchunfu,  it so sorry to said that code style already add in https://github.com/InterestingLab/seatunnel/pull/710. But you could still go and see if some necessary rule we need but forget. you could still add it by create a new issue and submit a PR. You could named it `Add checkstyle XXX to codebase`, but for now I have to close this issue because we already have code style checker in our codebase.
