### ISSUE TITLE
[Feature][flink] Improve flink version

### ISSUE THREAD

**Issue by ghost** [InterestingLab/seatunnel#709]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

SeaTunnel is based on flink 1.9, it's a too old version for most users.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Hi, let's focus on the discussion in #788
