### ISSUE TITLE
[Feature][Docker] Provide a docker image for quick-start that packaging spark and flink

### ISSUE THREAD

**Issue by yx91490** [InterestingLab/seatunnel#715]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

As the title says, this image can only be used for quick start or local development but not for production.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
Good suggestion ! Looking forward your contribution.
