### ISSUE TITLE
[Bug] error: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${ta})

### ISSUE THREAD

**Issue by x956606865** [InterestingLab/seatunnel#719]
### Search before asking

- [X] I had searched in the [issues](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I was try to use dynamic vars to run task.
I use the var{xxx="xx"} block to define vars, and get value by ${var->xxx}, It works fine.
But when I use -i xxx="xx" in the command to define vars and get value by ${xxx}, It will throw this error
`error: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${xxx})`

### SeaTunnel Version

1.5.5

### SeaTunnel Config

```conf
spark {
  spark.streaming.batchDuration = 5
  spark.app.name = "table"
  spark.ui.port = 13000
}
input {
       jdbc {
		driver = "org.postgresql.Driver"
		url = "jdbc:postgresql://..."
		user = "postgres"
		password = "..."
                table = ${xxx}
		result_table_name = "company1"
		jdbc.fetchsize = 500
	}

}

filter {
}

output {
   stdout {}
}
```

### Running Command

```shell
..//bin/start-seatunnel.sh --master local --deploy-mode client --config ./test.conf -i xxx=xx
```

### Error Exception

```log
Plugin[io.github.interestinglab.waterdrop.input.batch.Jdbc] contains invalid config, error: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${xxx})
```

### Flink or Spark Version

spark 2.4.8

### Java or Scala Version

1.8.0_292

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by RickyHuo** [comment]
@x956606865  You must use like this

> table = ""${field}""

**Comment by x956606865** [comment]
@RickyHuo

I changed the conf file to :
`
 jdbc {
		driver = "org.postgresql.Driver"
		url = "jdbc:postgresql://..."
		user = "postgres"
		password = "..."
                table = ""${xxx}""
		result_table_name = "company1"
		jdbc.fetchsize = 500
	}
`

But I still get the error:
`
Plugin[io.github.interestinglab.waterdrop.input.batch.Jdbc] contains invalid config, error: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigConcatenation(""${xxx}"")
`

**Comment by RickyHuo** [comment]
I think this is a bug due to project renamed.

**Comment by x956606865** [comment]
> I think this is a bug due to project renamed.

So what can I do to make it work? Or maybe I can only wait for the next versions release?

**Comment by RickyHuo** [comment]
@x956606865 you can try [Stable]v1.5.3 or wait for the next version， we will fix it as soon as possible.

**Comment by x956606865** [comment]
> @x956606865 you can try [Stable]v1.5.3 or wait for the next version， we will fix it as soon as possible.

1.5.3 works fine, thanks...
