### ISSUE TITLE
[Feature][Module Name] Any ideas about support oracle？

### ISSUE THREAD

**Issue by hzwcome** [InterestingLab/seatunnel#730]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Some databases are Oracle, and it would be great if you could import and export directly!

### Usage Scenario

Oracle->ClickHouse

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
We will provide SQL plug-in later, if you need it, you can add it yourself, we don’t need to show support for Oracle.

**Comment by hzwcome** [comment]
Okay, just a few ideas. Thank you
