### ISSUE TITLE
[Feature][Package] Some packages prefix is 'waterdrop' 

### ISSUE THREAD

**Issue by choucmei** [InterestingLab/seatunnel#731]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Some packages prefix is 'waterdrop' , Maybe use 'seatunnel' be better.
forexample : io.github.interestinglab.waterdrop.spark.batch

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
It would be fix after we enter incubator, am I right? @CalvinKirs ?

**Comment by CalvinKirs** [comment]
> It would be fix after we enter incubator, am I right? @CalvinKirs ?

This question will not be revised, for the time being, we will revise it uniformly after entering the incubator later.
