### ISSUE TITLE
[Online-Meeting]2.0 Roadmap

### ISSUE THREAD

**Issue by CalvinKirs** [InterestingLab/seatunnel#803]
Hi all,
We plan to start a community meeting at 11:00 on December 18 (UTC +8). We have established a list of topics to be discussed on google docs. Welcome everyone to list the issues you want to discuss in advance. The content of the topics is arbitrary, but you need to create ISSUE in advance, follow-up we will synchronize the relevant discussion process and results to ISSUE, and finally, we will categorize it on the wiki, thx

https://docs.google.com/document/d/1bXyZGt0g8f8_-d9Oj7oMx9BdWSjf8oJYZgNmoEooj8I/edit?usp=sharing

CalvinKirs invites you to a meeting on Tencent Meeting
Meeting Topic: SeaTunnel Meeting
Meeting Time: 2021/12/18 11:00-12:00 (GMT+08:00) China Standard Time - Beijing

Click the link to join the meeting or to add it to your meeting list:
https://meeting.tencent.com/dm/R3KKAnB9NiF4

#TencentMeeting：423-642-965

Copy this invitation and open in Tencent Meeting app (V2.13 or later) to join the meeting

**Comment by leo65535** [comment]
hi @CalvinKirs, how to add to slack chat room?

**Comment by CalvinKirs** [comment]
> 

Hi, we will create it later (wait until the code warehouse migration is completed)

**Comment by CalvinKirs** [comment]
> hi @CalvinKirs, how to add to slack chat room?

Hi, we will create it later (wait until the code warehouse migration is completed)

**Comment by CalvinKirs** [comment]
Related issues are tracked in specific issues.
