### ISSUE TITLE
[Feature][ctl] Introduce jcommander framework to seatunnel project

### ISSUE THREAD

**Issue by leo65535** [InterestingLab/seatunnel#813]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently, the seatunnel-core-base module is hard to scale inclusing(parse the args, add new command),

Here, introduce jcommander framework to replace `scopt`, https://jcommander.org/
- JCommander is an annotation-based library for parsing command-line parameters
- With JCommander, we can offload tricky tasks such as parsing, validation, and type conversions, to allow us to focus on our logic.
- `scopt` is written by scala, we can not use it in java.
- JCommander is released under the Apache 2.0 license.

```
class TestCommand {
    @Parameter(names={"--length", "-l"})
    int length;
    @Parameter(names={"--size", "-s"})
    int size;
}
```

### Related issues

#798

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
discuss link : https://lists.apache.org/thread/ffdgbz9k1qj74h90bd2fkqq8m0o28mqn

**Comment by garyelephant** [comment]
@CalvinKirs Hi Calvin, to be clear, typesafe config is for config managment, jcommander and scopt is for comand line parsing, they are not relevant. jcommander is for java while scopt is for scala. So I think it's a good idea to replace scopt with jcommander.

**Comment by CalvinKirs** [comment]
> @CalvinKirs Hi Calvin, to be clear, typesafe config is for config managment, jcommander and scopt is for comand line parsing, they are not relevant. jcommander is for java while scopt is for scala. So I think it's a good idea to replace scopt with jcommander.

Thanks for your clarification, please ignore me.

**Comment by leo65535** [comment]
Thanks @garyelephant @CalvinKirs.
