### ISSUE TITLE
[Feature][Plugin]Flink JdbcSource Information add BIT mapping

### ISSUE THREAD

**Issue by WJustHM** [InterestingLab/seatunnel#829]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The jdbcInputFormat lacks the BIT corresponding type

### Usage Scenario

The jdbcInputFormat lacks the BIT corresponding type
![image](https://user-images.githubusercontent.com/17983240/146709768-21a19ac7-8204-4366-a5bf-2007bc3147eb.png)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by CalvinKirs** [comment]
Discuss on #830
