### ISSUE TITLE
[Feature][project] Change project version to 2.0.5-SNAPSHOT

### ISSUE THREAD

**Issue by leo65535** [InterestingLab/seatunnel#865]
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

SeaTunnel project use a fixed version number in pom file, a fixed version means the version is stable. So, I suggest we can use `2.0.4-SNAPSHOT` to representative dev branch.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by leo65535** [comment]
cc @garyelephant @CalvinKirs @RickyHuo

**Comment by wuchunfu** [comment]
+1

**Comment by CalvinKirs** [comment]
+1 it should be 2.0.5-SNAPSHOT, we have released 2.0.4

**Comment by leo65535** [comment]
> it should be 2.0.5-SNAPSHOT, we have released 2.0.4

Got, thanks for reminding me.
